export const restaurantFieldSchema = Object.freeze({
  name:"식당명",englishName:"영문명",category:"카테고리",area:"지역",address:"주소",mapUrl:"지도 링크",officialUrl:"공식 웹사이트",reservationUrl:"예약 링크",image:"대표 이미지",cuisine:"음식 유형",priceRange:"가격대",audience:"추천 대상",occasion:"추천 상황",hoursCheckedAt:"운영시간 확인일",updatedAt:"최종 업데이트 날짜",sponsored:"광고·제휴 여부",editorReason:"시드니픽 선정 이유",status:"현재 게시 상태"
});
export const restaurantRecords = [];

const official={food:"https://www.sydney.com/things-to-do/food-and-drink",allergy:"https://www.foodauthority.nsw.gov.au/consumer/life-events-and-food/allergy-and-intolerance",standards:"https://www.foodstandards.gov.au/consumer/foodallergies/food-allergen-portal"};
const mapSearch=(query)=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}`;

const areas=[
  {name:"서큘러키",tags:"harbour special",time:"하버 산책 전후·공연 또는 페리 일정 전",route:"오페라하우스와 더 록스 사이에서 이동 방향을 기준으로 선택",types:"하버뷰·해산물·브런치·빠른 식사",reserve:"창가·저녁·주말 예약 여부 확인",areaUrl:"/areas/circular-quay"},
  {name:"더 록스",tags:"harbour area",time:"골목 산책 전후·하버 야경 전",route:"서큘러키 서쪽과 하버브리지 주변 보행 동선 안에서 선택",types:"펍 스타일·브런치·카페·저녁 식사",reserve:"행사·마켓 날짜와 저녁 혼잡 확인",areaUrl:"/areas/the-rocks"},
  {name:"달링하버",tags:"harbour family",time:"박물관·워터프런트 일정 사이",route:"다음 시설과 보행교 위치를 지도에서 먼저 확인",types:"가족 식사·해산물·캐주얼 다이닝",reserve:"주말·행사일과 단체 좌석 확인",areaUrl:null},
  {name:"바랑가루",tags:"harbour special",time:"수변 산책과 저녁 풍경을 잇는 시간",route:"더 록스 또는 달링하버 방향 중 다음 이동지에 맞춰 선택",types:"워터프런트·특별한 날·바와 다이닝",reserve:"저녁·창가·야외석 조건 확인",areaUrl:null},
  {name:"시드니 CBD",tags:"city solo korean",time:"쇼핑·업무지구 이동 사이의 점심과 저녁",route:"숙소와 다음 역·트램 정류장 사이 거리 확인",types:"한식·아시안·카페·혼자 식사",reserve:"점심 피크와 주방 마감 확인",areaUrl:null},
  {name:"본다이비치",tags:"beach brunch",time:"해변 산책 전 아침 또는 코스털 워크 후",route:"걷기 시작점·복귀 정류장과 같은 방향인지 확인",types:"브런치·카페·가벼운 식사",reserve:"주말 대기·실내석·주방 마감 확인",areaUrl:"/areas/bondi-beach"},
  {name:"맨리",tags:"beach brunch family",time:"페리 도착 후 또는 해변 산책 뒤",route:"선착장과 해변 사이, 귀환 페리 시간을 기준으로 선택",types:"브런치·카페·가족 식사·테이크아웃",reserve:"귀환 시간과 주말 대기 확인",areaUrl:"/areas/manly"},
  {name:"블루마운틴",tags:"daytrip family",time:"전망·산책과 귀환 교통 사이",route:"카툼바권 이동과 역·집결지 복귀 시간을 우선",types:"카페·가벼운 점심·테이크아웃",reserve:"당일 운영 여부와 주방 마감 확인",areaUrl:"/areas/blue-mountains"}
];

export const foodPages=[
  {slug:"by-area",title:"시드니 지역별 맛집 가이드 | 여행 동선별 식당 찾기 | 시드니픽",description:"서큘러키, 더 록스, CBD, 본다이, 맨리 등 시드니 여행 동선별로 식사 지역을 고르는 방법을 안내합니다.",h1:"시드니 지역별 맛집 찾기",eyebrow:"EAT BY AREA",lead:"식당 하나를 위해 동선을 꺾기보다 오늘 방문할 지역에서 식사하기 좋은 시간과 이동 방향부터 정하세요.",image:"https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&q=82&w=2000",alt:"다양한 음식을 함께 차린 시드니의 식탁",kind:"area",faqs:[["지역별 식당은 어떤 기준으로 찾나요?","관광지 이름만 검색하지 말고 다음 목적지, 도보 거리, 예약 필요성, 주방 마감과 당일 운영 여부를 함께 확인하세요."],["왜 식당 순위가 없나요?","상호·운영정보·가격을 검증하지 않은 상태에서 순위를 만들지 않습니다. 검증된 매장은 데이터 확인 뒤 게시합니다."],["혼잡시간은 어디서 확인하나요?","공식 웹사이트의 예약 가능 시간과 지도 서비스의 최신 운영 상태를 교차 확인하세요."]]},
  {slug:"brunch-cafes",title:"시드니 브런치·카페 가이드 | 주문과 이용 팁 | 시드니픽",description:"호주 카페 주문, 브런치와 일반 카페의 차이, 해변 카페·혼자 방문·알레르기 메뉴 확인 기준을 정리합니다.",h1:"시드니 브런치와 카페 선택 가이드",eyebrow:"BRUNCH & COFFEE",lead:"사진 속 분위기보다 주문 방식, 주방 마감, 대기와 알레르기 대응을 먼저 확인하면 아침 동선이 훨씬 편해집니다.",image:"https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&q=82&w=2000",alt:"자연광이 드는 카페 내부와 커피",kind:"brunch",faqs:[["카페와 브런치 식당은 어떻게 다른가요?","커피와 간단한 베이커리 중심인지, 별도 주방과 식사 메뉴를 운영하는지 확인하세요. 같은 영업시간이라도 주방 마감은 다를 수 있습니다."],["주말에는 꼭 예약해야 하나요?","매장 정책과 지역에 따라 다릅니다. 예약 가능 여부, 현장 대기 방식과 주방 마감을 공식 채널에서 확인하세요."],["알레르기 메뉴는 메뉴판만 보면 되나요?","메뉴 표시만 추정하지 말고 예약·주문 시 직원에게 알레르기와 교차접촉 가능성을 직접 확인하세요."]]},
  {slug:"harbour-dining",title:"시드니 하버뷰 레스토랑 선택 가이드 | 시드니픽",description:"오페라하우스와 하버브리지 전망, 서큘러키·더 록스·바랑가루, 좌석·예약·복장·날씨 기준을 비교합니다.",h1:"시드니 하버뷰 레스토랑 선택 가이드",eyebrow:"DINING WITH A VIEW",lead:"‘하버뷰’라는 한 단어보다 어떤 랜드마크가 보이는지, 실내·야외와 창가 좌석 조건, 취소 정책을 예약 전에 확인하세요.",image:"https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&q=82&w=2000",alt:"저녁 식사를 위해 정돈된 레스토랑 테이블",kind:"harbour",faqs:[["창가 좌석을 예약하면 확정되나요?","요청과 확정은 다를 수 있습니다. 예약 화면과 레스토랑의 좌석 보장 조건을 확인하고 특별 요청의 처리 방식을 문의하세요."],["오페라하우스 전망과 하버브리지 전망 중 무엇이 좋나요?","기념사진과 보고 싶은 랜드마크가 다릅니다. 식당 위치와 좌석 방향을 지도·공식 사진으로 확인하세요."],["비 오는 날 하버뷰 식사를 취소해야 하나요?","실내 좌석의 실제 전망, 야외석 대체 가능 여부와 취소 정책을 먼저 확인한 뒤 결정하세요."]]},
  {slug:"korean-food",title:"시드니 한식당 찾기 | 지역·메뉴·예약 가이드 | 시드니픽",description:"시드니 CBD와 한식 탐색 권역, 숙소 거리, 메뉴·가격·포장·운영시간·리뷰를 확인하는 방법을 안내합니다.",h1:"시드니에서 한식당 찾는 방법",eyebrow:"KOREAN FOOD IN SYDNEY",lead:"‘한국인 1위’ 같은 순위 대신 숙소와의 거리, 필요한 메뉴, 영업 여부와 포장·예약 조건을 직접 확인하는 방법을 안내합니다.",image:"https://images.unsplash.com/photo-1498654896293-37aacf113fd9?auto=format&fit=crop&q=82&w=2000",alt:"여러 반찬과 함께 차려진 한식 상차림",kind:"korean",faqs:[["시드니 한식당은 어디서 찾기 쉬운가요?","CBD와 인접 도심권을 출발점으로 지도에서 현재 영업 상태와 숙소 이동 시간을 확인하세요. 밀집 범위는 계속 달라질 수 있습니다."],["최신 리뷰만 보면 되나요?","최근 리뷰라도 개인 취향과 방문 시점이 다릅니다. 반복되는 운영 관련 의견을 참고하되 공식 메뉴·예약·영업 안내를 우선하세요."],["아이·부모님과 방문할 때 무엇을 보나요?","맵기 조절, 국물·밥 메뉴, 계단·좌석 접근성, 예약과 포장 가능 여부를 미리 확인하세요."]]}
];

const header=`<header class="site-header"><a class="brand" href="/" aria-label="시드니픽 홈"><strong>SYDNEY PICK</strong><span>시드니픽</span></a><button class="menu-toggle" aria-label="메뉴 열기" aria-expanded="false"><span></span><span></span></button><nav class="desktop-nav" aria-label="주요 메뉴"><a href="/itineraries">여행 일정</a><a href="/areas">지역별 픽</a><a href="/food" aria-current="page">맛집·카페</a><a href="/travel-prep">여행 준비</a><a href="/#shopping">쇼핑픽</a><a href="/#magazine">픽 매거진</a></nav><a class="guide-button" href="/#guide">무료 여행 가이드 <span>→</span></a><nav class="mobile-menu" aria-label="모바일 메뉴"><a href="/itineraries">여행 일정</a><a href="/areas">지역별 픽</a><a href="/food">맛집·카페</a><a href="/travel-prep">여행 준비</a><a href="/#shopping">쇼핑픽</a><a href="/#magazine">픽 매거진</a><a href="/#guide">무료 여행 가이드</a></nav></header>`;
const footer=`<footer><div class="wrap footer-grid"><div class="footer-brand"><a class="brand" href="/"><strong>SYDNEY PICK</strong><span>시드니픽</span></a><p>한국인을 위한 시드니 자유여행 가이드.<br>더 적게 헤매고, 더 오래 기억하세요.</p></div><nav><strong>여행 일정</strong><a href="/itineraries">전체 일정</a><a href="/itineraries/sydney-5n6d">5박 6일</a></nav><nav><strong>지역별 픽</strong><a href="/areas">지역 보기</a><a href="/areas/circular-quay">서큘러키</a></nav><nav><strong>맛집·카페</strong><a href="/food">탐색 허브</a><a href="/food/by-area">지역별</a><a href="/food/brunch-cafes">브런치·카페</a></nav><nav><strong>여행 준비</strong><a href="/travel-prep">준비 가이드</a><a href="/travel-prep/checklist">체크리스트</a></nav></div><div class="wrap footer-bottom"><p>© 2026 SYDNEY PICK. 운영정보와 가격은 방문 전 공식 채널을 확인하세요.</p></div></footer>`;
const safeJson=value=>JSON.stringify(value).replaceAll("<","\\u003c");
const faqSchema=faqs=>({"@context":"https://schema.org","@type":"FAQPage",mainEntity:faqs.map(([name,text])=>({"@type":"Question",name,acceptedAnswer:{"@type":"Answer",text}}))});
const head=page=>{const path=page.slug?`/food/${page.slug}`:"/food";const url=`__SITE_URL__${path}`;const schemas=[{"@context":"https://schema.org","@type":"Article",headline:page.h1,description:page.description,url,inLanguage:"ko-KR",dateModified:"__LAST_UPDATED__",publisher:{"@type":"Organization",name:"시드니픽",url:"__SITE_URL__"}},{"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"홈",item:"__SITE_URL__/"},{"@type":"ListItem",position:2,name:"맛집·카페",item:"__SITE_URL__/food"},...(page.slug?[{"@type":"ListItem",position:3,name:page.h1,item:url}]:[])]},faqSchema(page.faqs)];return`<!doctype html><html lang="ko"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${page.title}</title><meta name="description" content="${page.description}"><link rel="canonical" href="${url}"><meta property="og:type" content="article"><meta property="og:locale" content="ko_KR"><meta property="og:site_name" content="시드니픽"><meta property="og:title" content="${page.title}"><meta property="og:description" content="${page.description}"><meta property="og:url" content="${url}"><meta property="og:image" content="${page.image}"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="/public/favicon.svg"><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@500;600;700;800&family=Noto+Sans+KR:wght@400;500;600;700;800&display=swap"><link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/styles-pages.css"><link rel="stylesheet" href="/styles-food.css">${schemas.map(s=>`<script type="application/ld+json">${safeJson(s)}</script>`).join("")}</head>`};
const hero=(p,detail=true)=>`<main id="content"><section class="food-hero${detail?' detail-hero':' food-hub-hero'}"><img class="${detail?'detail-hero-image':''}" src="${p.image}" alt="${p.alt}"><div class="wrap food-hero-content${detail?' detail-hero-content':''}"><nav class="breadcrumb" aria-label="현재 위치"><a href="/">홈</a><span>›</span>${detail?'<a href="/food">맛집·카페</a><span>›</span>':''}<span>${detail?p.h1:"맛집·카페"}</span></nav><p class="eyebrow">${p.eyebrow}</p>${detail?`<h1 class="detail-hero-title">${p.h1}</h1>`:'<h1 class="food-hub-hero-title"><span>시드니 맛집과 카페,</span><span>여행 동선에 맞게 고르세요</span></h1>'}<p class="lead${detail?' detail-hero-lead':''}">${p.lead}</p></div><span class="food-credit${detail?' detail-hero-credit':''}">Photo: Unsplash</span></section>`;
const faq=p=>`<section class="food-section tint"><div class="wrap"><div class="food-heading"><h2>자주 묻는 질문</h2><p>화면에 표시된 질문과 답변만 FAQ 구조화 데이터에 포함합니다.</p></div><div class="faq-list">${p.faqs.map(([q,a])=>`<details><summary>${q}</summary><p>${a}</p></details>`).join("")}</div></div></section>`;
const sources=()=>`<section class="food-section"><div class="wrap"><div class="food-source"><div><h2>공식 정보 확인</h2><p>영업시간·메뉴·가격·예약·알레르기 정보는 변경될 수 있습니다. 매장의 공식 채널과 공공기관 안내를 방문 날짜 기준으로 확인하세요.</p><div class="food-updated">최종 업데이트: __LAST_UPDATED__</div></div><div class="food-source-links"><a href="${official.food}" target="_blank" rel="noreferrer">Sydney.com 음식·다이닝 ↗</a><a href="${official.allergy}" target="_blank" rel="noreferrer">NSW Food Authority 알레르기 ↗</a><a href="${official.standards}" target="_blank" rel="noreferrer">FSANZ 알레르기 정보 ↗</a></div></div></div></section>`;
const status=`<span class="editor-status">에디터 확인 후 업데이트</span>`;

export function renderFoodHub(){
 const p={title:"시드니 맛집·카페 가이드 | 지역별 음식과 브런치 | 시드니픽",description:"시드니 여행 동선과 식사 목적, 분위기, 예약 필요성에 맞춰 맛집과 카페를 선택하는 가이드입니다.",h1:"시드니 맛집과 카페, 여행 동선에 맞게 고르세요",eyebrow:"EAT WELL, TRAVEL LIGHT",lead:"유명하다는 이유만으로 멀리 이동하기보다 오늘 방문할 지역, 식사 목적, 예산과 분위기에 맞는 곳을 선택할 수 있도록 안내합니다.",image:"https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&q=82&w=2000",alt:"여러 음식이 자연스럽게 차려진 여행 식탁",faqs:[["왜 추천 식당 목록이 없나요?","현재는 상호·주소·운영정보가 검증된 매장만 게시하기 위한 구조를 먼저 만들었습니다. 확인 전에는 임의의 순위나 가격을 노출하지 않습니다."],["가격대는 어디서 확인하나요?","매장 공식 메뉴와 예약 화면을 우선 확인하고, 방문 날짜에 맞는 최신 정보를 다시 확인하세요."],["광고 매장도 추천처럼 보이나요?","아니요. 향후 광고·제휴 콘텐츠는 편집 추천과 구분되는 배지와 데이터 필드로 표시합니다."]]};
 const cats=[
  ["지역별","오늘 가는 지역에서 찾기","동선 중심·선택 폭 다양","/food/by-area","area"],["아침·브런치","해변·산책 전후 여유로운 식사","밝고 캐주얼","/food/brunch-cafes","brunch"],["카페","짧은 휴식·테이크아웃·혼자 방문","지역에 따라 다양","/food/brunch-cafes","cafe"],["하버뷰","기념일·부모님·야경","전망 중심·예약 가능성 높음","/food/harbour-dining","harbour special"],["스테이크·해산물","저녁 한 끼에 집중할 때","캐주얼부터 포멀까지","/food/by-area","dinner"],["한식","장기 여행·가족·국물 메뉴 필요","편안하고 익숙한 식사","/food/korean-food","korean"],["가족 식사","아이·부모님과 이동을 줄일 때","좌석·접근성 우선","/food/by-area","family"],["혼자 식사","짧은 식사·카운터·테이크아웃","부담 없는 이용","/food/by-area","solo"],["특별한 날","기념일·부모님 여행","좌석과 서비스 확인","/food/harbour-dining","special"],["예약이 필요한 식당","주말·저녁·전망 좌석","예약·취소조건 우선","/food/harbour-dining","reserve"]
 ];
 const cards=cats.map((c,i)=>`<article class="food-card ${i===0?'feature':i===3?'wide':''}" data-food-card="${c[4]}"><small>${String(i+1).padStart(2,"0")} · FIND YOUR TABLE</small><h3>${c[0]}</h3><p>${c[1]}</p><dl><div><dt>예상 분위기</dt><dd>${c[2]}</dd></div><div><dt>예약 확인</dt><dd>공식 채널 확인 후 입력</dd></div><div><dt>가격대</dt><dd>검증 후 입력</dd></div></dl>${status}<a href="${c[3]}">자세히 보기 →</a></article>`).join("");
 return`${head(p)}<body class="food-page"><a class="skip-link" href="#content">본문으로 건너뛰기</a>${header}${hero(p,false)}<nav class="food-filters" aria-label="맛집 카테고리 필터"><button class="active" data-food-filter="all" aria-pressed="true">전체</button><button data-food-filter="area" aria-pressed="false">지역별</button><button data-food-filter="brunch" aria-pressed="false">브런치</button><button data-food-filter="cafe" aria-pressed="false">카페</button><button data-food-filter="harbour" aria-pressed="false">하버뷰</button><button data-food-filter="korean" aria-pressed="false">한식</button><button data-food-filter="family" aria-pressed="false">가족</button><button data-food-filter="special" aria-pressed="false">특별한 날</button></nav><section class="food-section"><div class="wrap"><div class="food-heading"><h2>목적부터 고르는<br>열 가지 탐색 기준</h2><p>실제 매장 정보가 확인되기 전에는 상호·주소·후기·평점·가격을 사실처럼 표시하지 않습니다.</p></div><div class="food-category-grid">${cards}</div></div></section><section class="food-photo-band"><img src="https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&q=82&w=1500" alt="따뜻한 자연광 아래 놓인 커피"><div class="food-photo-copy"><p class="eyebrow">ROUTE FIRST</p><h2>식당을 찾기 전에<br>오늘의 동선을 정하세요</h2><p>서큘러키·더 록스, 달링하버·바랑가루, CBD, 본다이, 맨리, 블루마운틴까지 다음 목적지와 가까운 구역을 먼저 고릅니다.</p><a class="page-button" href="/food/by-area">지역별 탐색 시작 →</a></div></section><section class="food-section"><div class="wrap"><div class="ad-zone"><div><p class="eyebrow">AD · AFFILIATE READY</p><h2>광고와 편집 추천을 분리합니다</h2><p>예약 제휴, 식당 광고, 체험단, 추천 매장, 쿠폰, 일정 패키지와 한인업체 등록을 위한 데이터 필드를 준비했습니다.</p><small>확정 제휴가 없으므로 업체·혜택·예약 링크를 노출하지 않습니다.</small></div><span class="ad-badge">제휴 준비 중</span></div></div></section>${faq(p)}${sources()}</main>${footer}<script src="/assets/food.js" defer></script></body></html>`;
}

function renderAreaPage(p){const rows=areas.map(a=>`<article class="food-guide-row" data-food-card="${a.tags}"><h3>${a.name}</h3><div><p><b>좋은 시간</b> · ${a.time}</p><p><b>여행 동선</b> · ${a.route}</p><p><b>추천 유형</b> · ${a.types}</p><p><b>예약·혼잡 확인</b> · ${a.reserve}</p>${status}</div><div class="food-guide-actions"><a href="${mapSearch(`${a.name} Sydney restaurants`)}" target="_blank" rel="noreferrer">지도에서 거리 확인 ↗</a>${a.areaUrl?`<a href="${a.areaUrl}">지역 상세 가이드 →</a>`:'<span>지역 상세 콘텐츠 준비 중</span>'}</div></article>`).join("");return`${head(p)}<body class="food-page"><a class="skip-link" href="#content">본문으로 건너뛰기</a>${header}${hero(p)}<nav class="food-filters" aria-label="지역 필터"><button class="active" data-food-filter="all" aria-pressed="true">전체</button><button data-food-filter="harbour" aria-pressed="false">하버·도심</button><button data-food-filter="beach" aria-pressed="false">해변</button><button data-food-filter="family" aria-pressed="false">가족</button><button data-food-filter="solo" aria-pressed="false">혼자</button></nav><section class="food-section"><div class="wrap"><div class="food-heading"><h2>여덟 지역,<br>서로 다른 식사 타이밍</h2><p>관광지와 식당가의 거리는 지도에서 실제 보행 경로로 확인하고, 운영시간·혼잡·예약은 매장 공식 채널을 우선합니다.</p></div><div class="food-guide-list">${rows}</div></div></section><section class="food-section tint"><div class="wrap"><div class="food-heading"><h2>검증 매장 데이터 구조</h2><p>식당명, 영문명, 카테고리, 지역, 주소, 지도·공식·예약 링크, 이미지, 음식 유형, 가격대, 대상, 상황, 확인일, 제휴 여부, 선정 이유와 게시 상태를 분리해 관리합니다.</p></div><div class="food-notes"><article class="food-note"><h3>현재 게시 상태</h3><p>검증된 상세 식당 레코드가 아직 없어 빈 데이터 배열로 유지합니다. 자료가 없는 필드는 화면에 억지로 표시하지 않습니다.</p>${status}</article><article class="food-note"><h3>관련 일정</h3><p>5박 6일의 날짜별 식사 위치를 지역 동선과 함께 확인하세요.</p><a href="/itineraries/sydney-5n6d">5박 6일 일정 보기 →</a></article></div></div></section>${faq(p)}${sources()}</main>${footer}<script src="/assets/food.js" defer></script></body></html>`}

const detailContent={
 brunch:{intro:"브런치는 식사 주방 운영 여부가 중요하고, 일반 카페는 커피·베이커리·테이크아웃 중심일 수 있습니다.",table:[["주문 방식","카운터 주문인지 테이블 서비스인지 입장 후 안내 확인"],["커피 선택","에스프레소 기반 음료, 우유 종류, 크기와 추가 비용을 메뉴에서 확인"],["혼자 방문","좌석 회전·카운터석·테이크아웃과 짐 보관 가능 여부 확인"],["해변 카페","바다 전망보다 산책 시작점·복귀 정류장·실내 대안 우선"],["주말 이용","예약 가능 여부, 현장 대기 방식과 주방 마감 확인"],["알레르기·채식","직원에게 성분과 교차접촉 가능성을 직접 질문"],["테이크아웃","용기·대기·해변 반입 및 쓰레기 처리 기준 확인"]],notes:[["사진보다 먼저 볼 것",["공식 영업일과 당일 휴무", "주방 마감시간", "예약·워크인 정책", "실내·야외 좌석", "알레르기 대응"]],["지역과 연결",["본다이비치 산책 전후", "맨리 페리 귀환 전", "CBD 체크아웃·쇼핑 사이"]]],links:[["본다이비치","/areas/bondi-beach"],["맨리","/areas/manly"]]},
 harbour:{intro:"전망의 방향과 좌석 조건, 방문 시간대가 식사의 인상을 결정합니다. 공식 사진과 지도를 함께 확인하세요.",table:[["오페라하우스 전망","랜드마크 정면·측면 여부와 좌석 방향 확인"],["하버브리지 전망","다리 구조와 야경을 볼 수 있는 방향인지 확인"],["서큘러키","랜드마크 접근은 편하지만 관광 동선과 혼잡 고려"],["더 록스","역사 골목·브리지 방향 산책과 함께 구성"],["바랑가루","현대적 워터프런트와 저녁 산책에 연결"],["점심과 저녁","채광·메뉴·복장·예약금 조건의 차이 확인"],["실내와 야외","비·강풍·온도와 야외석 대체 가능 여부 확인"]],notes:[["예약 전에 반드시",["창가 좌석 요청과 보장 여부", "복장 규정", "예약금·선결제", "취소·노쇼 정책", "기념일 요청 처리"]],["부모님·기념일",["계단과 접근성", "소음과 좌석 간격", "공연·귀환 교통까지의 시간", "우천 시 실내 전망"]]],links:[["서큘러키","/areas/circular-quay"],["더 록스","/areas/the-rocks"]],ad:true},
 korean:{intro:"장기 여행자, 부모님·아이 동반, 매운 음식과 국물이 필요한 날에는 숙소에서 무리 없는 거리와 메뉴 선택 폭을 먼저 봅니다.",table:[["CBD 탐색","숙소·역·다음 일정 사이의 실제 보행거리 확인"],["메뉴와 가격","공식 메뉴의 제공 단위·세트·추가 비용 확인"],["예약·포장","전화·공식 예약 채널과 포장 가능 여부 확인"],["영업시간","요일별 영업과 주방 마감, 공휴일 변동 확인"],["한국식·현지화 메뉴","메뉴 설명과 맵기·구성 차이를 확인하고 단정하지 않기"],["최신 리뷰","방문일·메뉴·서비스 상황을 구분하고 반복되는 변화만 참고"]],notes:[["추천 대상",["장기 여행자", "부모님과 여행", "아이와 여행", "매운 음식과 국물이 필요한 여행자", "체류 중 한식이 필요한 사람"]],["확인 순서",["숙소에서 거리", "필요한 메뉴", "오늘 영업 여부", "예약·포장", "공식 메뉴 가격"]]],links:[["시드니 CBD가 포함된 지역 허브","/areas"],["5박 6일 일정","/itineraries/sydney-5n6d"]]}
};
function renderGuidePage(p){const c=detailContent[p.kind];const table=`<div class="choice-table-wrap" tabindex="0"><table class="choice-table"><thead><tr><th>선택 기준</th><th>확인할 내용</th></tr></thead><tbody>${c.table.map(([a,b])=>`<tr><th>${a}</th><td>${b}</td></tr>`).join("")}</tbody></table></div>`;const notes=c.notes.map(([h,items])=>`<article class="food-note"><h3>${h}</h3><ul>${items.map(x=>`<li>${x}</li>`).join("")}</ul></article>`).join("");const ad=c.ad?`<section class="food-section"><div class="wrap"><div class="ad-zone"><div><p class="eyebrow">AD · AFFILIATE READY</p><h2>예약 제휴 영역</h2><p>추후 검증된 예약 제휴와 광고 상품을 연결할 수 있습니다. 현재는 제휴처·할인·예약 링크가 없습니다.</p><small>광고와 편집 추천은 서로 다른 배지와 sponsored 데이터로 구분합니다.</small></div><span class="ad-badge">제휴 준비 중</span></div></div></section>`:"";return`${head(p)}<body class="food-page"><a class="skip-link" href="#content">본문으로 건너뛰기</a>${header}${hero(p)}<section class="food-section"><div class="wrap"><div class="food-heading"><h2>선택 기준부터<br>차근차근</h2><p>${c.intro}</p></div>${table}</div></section><section class="food-section tint"><div class="wrap"><div class="food-notes">${notes}</div><div class="food-heading" style="margin-top:50px"><h2>검증 매장<br>추가 템플릿</h2><p>매장명·주소·메뉴·가격·예약 링크는 확인 전까지 비워 둡니다. 광고·제휴 여부와 편집 선정 이유를 별도 필드로 관리합니다.</p></div>${status}</div></section>${ad}<section class="food-section"><div class="wrap"><div class="food-heading"><h2>관련 지역과 일정</h2><p>식사만을 위해 우회하지 않도록 공개된 지역 상세페이지와 일정에 연결합니다.</p></div><div class="food-notes">${c.links.map(([n,u])=>`<article class="food-note"><h3>${n}</h3><a href="${u}">가이드 보기 →</a></article>`).join("")}</div></div></section>${faq(p)}${sources()}</main>${footer}<script src="/assets/food.js" defer></script></body></html>`}

export function renderFoodPage(p){return p.kind==="area"?renderAreaPage(p):renderGuidePage(p)}
