function initMagazine(){
 const header=document.querySelector('.site-header'),menu=document.querySelector('.menu-toggle');menu?.addEventListener('click',()=>{const open=header?.classList.toggle('menu-open');menu.setAttribute('aria-expanded',String(Boolean(open)))});document.querySelectorAll('.mobile-menu a').forEach(a=>a.addEventListener('click',()=>header?.classList.remove('menu-open')));
 const more=document.querySelector('[data-mag-more]'),cards=[...document.querySelectorAll('[data-mag-card]')];if(more){let shown=6;const update=()=>{cards.forEach((c,i)=>c.hidden=i>=shown);more.hidden=shown>=cards.length};update();more.addEventListener('click',()=>{shown+=6;update()})}
 const form=document.querySelector('[data-mag-search]'),results=document.querySelector('[data-search-results]'),summary=document.querySelector('[data-search-summary]'),data=window.__MAGAZINE_INDEX__||[];
 const card=p=>`<article class="mag-card"><a href="/magazine/${p.slug}"><img src="${p.heroImage}" alt="${p.heroImageAlt.replace(/[<>]/g,'')}"><div><span>${p.categoryName}</span><h3>${p.title}</h3><p>${p.description}</p><small>${p.updatedAt} · ${p.readingTime}</small></div></a></article>`;
 const runSearch=()=>{if(!form||!results||!summary)return;const query=new URLSearchParams(location.search).get('q')?.trim()||'';form.querySelector('input').value=query;if(!query){summary.textContent='검색어를 입력하면 제목, 요약, 카테고리와 태그에서 찾아드립니다.';results.innerHTML='';return}const terms=query.toLowerCase().split(/\s+/).filter(Boolean),found=data.filter(p=>{const hay=[p.title,p.description,p.categoryName,...p.tags].join(' ').toLowerCase();return terms.every(t=>hay.includes(t))});summary.textContent=found.length?`“${query}” 검색 결과 ${found.length}개`:`“${query}”에 해당하는 글이 없습니다. 지역명, 교통, 일정처럼 더 짧은 단어로 검색해보세요.`;results.innerHTML=found.map(card).join('')};
 form?.addEventListener('submit',event=>{event.preventDefault();const query=form.querySelector('input').value.trim();history.replaceState({},'',query?`/magazine/search?q=${encodeURIComponent(query)}`:'/magazine/search');runSearch()});runSearch();
 document.querySelector('[data-copy-url]')?.addEventListener('click',async event=>{try{await navigator.clipboard.writeText(location.href);event.currentTarget.textContent='URL 복사 완료'}catch{event.currentTarget.textContent='복사할 수 없어요'}});
 document.querySelector('[data-mag-share]')?.addEventListener('click',async event=>{try{if(navigator.share)await navigator.share({title:document.title,url:location.href});else await navigator.clipboard.writeText(location.href);event.currentTarget.textContent='공유 완료'}catch(error){if(error?.name!=='AbortError')event.currentTarget.textContent='공유할 수 없어요'}})
}
if(typeof document!=='undefined'){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initMagazine,{once:true});else initMagazine()}
